"""Bench tooling (`local` mode + `zones` editor): the config-edit round trip
through the contract models, the save endpoint over real HTTP, and the
pipeline frame tap that feeds the preview. No camera, cv2, ffmpeg or cloud."""
import asyncio
import json
import shutil
import threading
import urllib.error
import urllib.request
from pathlib import Path

import pytest

from sentinel_edge.contracts import DeviceConfig
from sentinel_edge.local.zones_tool import ZonesServer, apply_zones, write_config

CONFIG = Path(__file__).resolve().parents[1] / "configs/examples/device-config.json"
CAM = "0190f3a1-1111-7000-8000-000000000001"


def _load() -> DeviceConfig:
    return DeviceConfig.model_validate_json(CONFIG.read_text(encoding="utf-8"))


# ---------------------------------------------------------------- apply_zones


def test_apply_zones_replaces_and_bumps_etag():
    config = _load()
    new = apply_zones(config, CAM, [
        {"name": "Door line", "polygon": [[0.1, 0.5], [0.9, 0.5]],
         "rules": [{"rule_type": "line_cross", "direction": "lr",
                    "classes": ["person"], "min_confidence": 0.6}]},
    ])
    cam = new.cameras[0]
    assert [z.name for z in cam.zones] == ["Door line"]
    assert cam.zones[0].zone_id  # autogenerated
    assert cam.zones[0].rules[0].direction == "lr"
    assert new.config_etag != config.config_etag
    # untouched fields survive the round trip
    assert new.device_id == config.device_id
    assert cam.rtsp_ref == config.cameras[0].rtsp_ref


def test_apply_zones_keeps_existing_zone_id():
    config = _load()
    zid = config.cameras[0].zones[0].zone_id
    new = apply_zones(config, CAM, [
        {"zone_id": zid, "name": "Renamed", "polygon": [[0.2, 0.2], [0.8, 0.8]],
         "rules": []},
    ])
    assert new.cameras[0].zones[0].zone_id == zid


def test_apply_zones_rejects_bad_polygon_and_unknown_camera():
    config = _load()
    with pytest.raises(ValueError, match="invalid"):
        apply_zones(config, CAM, [{"name": "bad", "polygon": [[0.5, 1.7]], "rules": []}])
    with pytest.raises(ValueError, match="unknown camera_id"):
        apply_zones(config, "nope", [])


def test_apply_zones_drops_junk_rule_fields():
    config = _load()
    new = apply_zones(config, CAM, [
        {"name": "L", "polygon": [[0.1, 0.5], [0.9, 0.5]],
         "rules": [{"rule_type": "line_cross", "direction": "", "dwell_s": None,
                    "bogus_from_page": 1}]},
    ])
    rule = new.cameras[0].zones[0].rules[0]
    assert rule.direction is None
    assert not hasattr(rule, "bogus_from_page")


# ---------------------------------------------------------------- HTTP save


def test_zones_server_save_roundtrip(tmp_path):
    config_path = tmp_path / "device-config.json"
    shutil.copy(CONFIG, config_path)
    server = ZonesServer(config_path, CAM, snapshot_jpeg=b"\xff\xd8fakejpeg")

    httpd = server.make_server(0)  # the real handler, ephemeral port
    port = httpd.server_address[1]
    t = threading.Thread(target=httpd.serve_forever, daemon=True)
    t.start()
    try:
        base = f"http://127.0.0.1:{port}"
        state = json.loads(urllib.request.urlopen(f"{base}/state").read())
        assert state["camera_id"] == CAM and len(state["zones"]) == 2

        body = json.dumps({"zones": [
            {"name": "Only line", "polygon": [[0.3, 0.1], [0.3, 0.9]],
             "rules": [{"rule_type": "line_cross", "direction": "both",
                        "classes": ["person"], "min_confidence": 0.5}]},
        ]}).encode()
        req = urllib.request.Request(f"{base}/save", data=body,
                                     headers={"Content-Type": "application/json"})
        out = json.loads(urllib.request.urlopen(req).read())
        assert out["ok"] is True

        on_disk = DeviceConfig.model_validate_json(config_path.read_text(encoding="utf-8"))
        assert [z.name for z in on_disk.cameras[0].zones] == ["Only line"]
        assert on_disk.config_etag == out["config_etag"]

        # invalid payload -> 400, file untouched
        bad = json.dumps({"zones": [{"name": "x", "polygon": [[2, 2], [3, 3]],
                                     "rules": []}]}).encode()
        req = urllib.request.Request(f"{base}/save", data=bad,
                                     headers={"Content-Type": "application/json"})
        with pytest.raises(urllib.error.HTTPError) as exc:
            urllib.request.urlopen(req)
        assert exc.value.code == 400
        still = DeviceConfig.model_validate_json(config_path.read_text(encoding="utf-8"))
        assert [z.name for z in still.cameras[0].zones] == ["Only line"]
    finally:
        httpd.shutdown()
        httpd.server_close()


def test_write_config_atomic(tmp_path):
    path = tmp_path / "c.json"
    config = _load()
    write_config(path, config)
    assert DeviceConfig.model_validate_json(path.read_text(encoding="utf-8")) == config
    assert list(tmp_path.glob("*.tmp")) == []


# ---------------------------------------------------------------- frame tap


def test_pipeline_frame_tap_sees_tracks_and_candidates(tmp_path, monkeypatch):
    """The preview hook receives every frame; on the simulate scenario it must
    observe live tracks and at least one rule firing, and a raising tap must
    disable itself without killing the pipeline."""
    from sentinel_edge.config import EdgeSettings, PipelineDefaults
    from sentinel_edge.main import CameraPipeline, Supervisor, _synthetic_frames

    monkeypatch.chdir(tmp_path)
    settings = EdgeSettings(data_dir=tmp_path / "data")
    defaults = PipelineDefaults(backend="mock", motion_min_fraction=0.0005,
                                min_object_px=8, clip_pre_s=0.5, clip_post_s=0.2,
                                rule_cooldown_s=5.0)
    config = DeviceConfig.model_validate_json(CONFIG.read_text(encoding="utf-8"))

    seen = {"frames": 0, "tracks": 0, "cands": 0}

    def tap(camera, frame, tracks, candidates, line_counts):
        seen["frames"] += 1
        seen["tracks"] += len(tracks)
        seen["cands"] += len(candidates)
        if seen["frames"] == 1:
            raise RuntimeError("tap blew up")  # must be contained + disabled

    async def go():
        sup = Supervisor(settings, defaults, frame_tap=tap)
        await sup.inference.start()
        cam = config.cameras[0]
        pipeline = CameraPipeline(
            cam, defaults, sup.inference, sup.queue, sup.spool, sup.health, sup,
            frame_source=_synthetic_frames(6.0, 10, (640, 360)), on_frame=tap)

        async def patch_encoders():
            while pipeline.recorder is None:
                await asyncio.sleep(0.01)
            async def fake(frames, fps, out_path):
                out_path.write_bytes(b"x")
            async def fake_t(frame, out_path):
                out_path.write_bytes(b"x")
            pipeline.recorder.encoder = fake
            pipeline.recorder.thumb_encoder = fake_t

        await asyncio.gather(pipeline.run(), patch_encoders())
        await sup.inference.stop()
        sup.queue.close()
        return pipeline

    pipeline = asyncio.run(go())
    # first call raised -> tap disabled on that pipeline
    assert pipeline.on_frame is None
    assert seen["frames"] == 1


def test_pipeline_frame_tap_collects_data(tmp_path, monkeypatch):
    from sentinel_edge.config import EdgeSettings, PipelineDefaults
    from sentinel_edge.main import CameraPipeline, Supervisor, _synthetic_frames

    monkeypatch.chdir(tmp_path)
    settings = EdgeSettings(data_dir=tmp_path / "data")
    defaults = PipelineDefaults(backend="mock", motion_min_fraction=0.0005,
                                min_object_px=8, clip_pre_s=0.5, clip_post_s=0.2,
                                rule_cooldown_s=5.0)
    config = DeviceConfig.model_validate_json(CONFIG.read_text(encoding="utf-8"))

    seen = {"frames": 0, "tracks": 0, "cands": 0}

    def tap(camera, frame, tracks, candidates, line_counts):
        assert camera.camera_id == CAM
        seen["frames"] += 1
        seen["tracks"] += len(tracks)
        seen["cands"] += len(candidates)

    async def go():
        sup = Supervisor(settings, defaults, frame_tap=tap)
        await sup.inference.start()
        cam = config.cameras[0]
        pipeline = CameraPipeline(
            cam, defaults, sup.inference, sup.queue, sup.spool, sup.health, sup,
            frame_source=_synthetic_frames(8.0, 10, (640, 360)), on_frame=tap)

        async def patch_encoders():
            while pipeline.recorder is None:
                await asyncio.sleep(0.01)
            async def fake(frames, fps, out_path):
                out_path.write_bytes(b"x")
            async def fake_t(frame, out_path):
                out_path.write_bytes(b"x")
            pipeline.recorder.encoder = fake
            pipeline.recorder.thumb_encoder = fake_t

        await asyncio.gather(pipeline.run(), patch_encoders())
        await sup.inference.stop()
        sup.queue.close()

    asyncio.run(go())
    assert seen["frames"] > 20      # tap fires per frame, gated frames included
    assert seen["tracks"] > 0       # the walking square was tracked
    assert seen["cands"] >= 1       # zone_enter / line_cross fired through the tap
